version: '3.3'
services:
  nginx:
    deploy:
      resources:
          limits:
              cpus: '0.5'
              memory: "1024M" 
    container_name: nginx_BACKEND_PATALI
    image: nginx:alpine
    ports:
      - 8001:80
    depends_on : 
      - app
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always 
  app:
    container_name: app_BACKEND_PATALI
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    restart: always 
  php:
    container_name: php_BACKEND_PATALI
    image: php:8.2-fpm-alpine
    depends_on : 
      - app
    volumes:
      - ./:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    restart: always 
  
